// GENERATED by packages/tokens/generate.mjs — do not edit by hand.
// Source: packages/tokens/tokens.json. Regenerate with:
//   npm run tokens:build
//
// One tokens file — every screen imports from here so future re-skinning
// is a single edit. Values chosen for a low-tech field user on a mid-
// range Android phone under variable lighting:
//   * 56px minimum tap target — matches Material 'large' spec and is
//     comfortable for users wearing gloves. Brief requires 56px min.
//   * 18px body minimum — legible at arm's length in bright sunlight;
//     16px was too small in field trials.
//   * Bond-green primary (#093D30) — carried over from Syncit brand
//     ramp; every other status colour is picked to sit against it.

export const theme = {
  colors: {
    // Syncit brand ramp
    bond:      "#093D30",
    kiln:      "#12876C",
    set:       "#3DDC97",
    cure:      "#B96A00",
    fault:     "#B42318",
    bench:     "#F5F7F6",
    ink:       "#0B1D18",
    inkMuted:  "#5A6B65",
    line:      "#D8DEDC",
    curBg:     "#FEF3C7",
    faultBg:   "#FEE4E2",
    white:     "#FFFFFF",

    // Legacy aliases — every existing screen imports `primary`,
    // `background`, `textMuted` etc. Kept pointing at the brand ramp
    // so nothing breaks on regeneration. New code should reference the
    // ramp names directly (`bond`, `bench`, `inkMuted`).
    primary:    "#093D30",
    primaryOn:  "#FFFFFF",
    background: "#FFFFFF",
    surface:    "#F5F7F6",
    text:       "#0B1D18",
    textMuted:  "#5A6B65",
    border:     "#D8DEDC",
    danger:     "#B42318",
    dangerBg:   "#FEE4E2",
    success:    "#12876C",
    focus:      "#12876C",
  },
  // Minimum tap target — brief requires 56px, matches Material spec
  // for "large" buttons and is comfortable for users wearing gloves.
  tap: 56,
  radius: 12,
  radii: {
    sm:   6,
    md:   12,
    lg:   20,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  type: {
    // 16 body minimum per brief; larger scale for titles because these
    // users often hold the phone at arm's length.
    bodySmall: 16,
    body:      18,
    button:    18,
    heading:   22,
    title:     28,
  },
} as const;

export type Theme = typeof theme;
