#!/usr/bin/env node
// Regenerate the design-token outputs from packages/tokens/tokens.json.
//
//   node packages/tokens/generate.mjs
//
// Emits:
//   packages/tokens/tailwind.tokens.mjs  — imported by tailwind.config.ts,
//                                          adds a `syncit.*` namespace so
//                                          existing shadcn HSL vars are
//                                          untouched.
//   mobile/src/theme.ts                  — full rewrite. Header comments
//                                          are hand-crafted here so the
//                                          reasoning behind the 56px tap
//                                          target and 18px body survives
//                                          regeneration.
//
// Idempotent — re-run after editing tokens.json.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = dirname(dirname(HERE));

async function ensureDir(path) {
  const dir = dirname(path);
  if (!existsSync(dir)) await mkdir(dir, { recursive: true });
}

async function main() {
  const raw = await readFile(join(HERE, "tokens.json"), "utf8");
  const tokens = JSON.parse(raw);

  await writeTailwindTokens(tokens);
  await writeMobileTheme(tokens);

  console.log("Design tokens regenerated.");
}

function colorHexMap(tokens) {
  const out = {};
  for (const [name, def] of Object.entries(tokens.colors)) {
    if (name.startsWith("$")) continue;
    out[name] = def.hex;
  }
  return out;
}

async function writeTailwindTokens(tokens) {
  const out = join(HERE, "tailwind.tokens.mjs");
  const colors = colorHexMap(tokens);
  const spacing = tokens.spacing;
  const radius = tokens.radius;
  const type = tokens.type;
  const tap = tokens.tap.min;
  const fonts = tokens.fonts;

  const body = `// GENERATED by packages/tokens/generate.mjs — do not edit by hand.
// Source: packages/tokens/tokens.json.

/** Consumed by tailwind.config.ts under the \`syncit\` namespace so
 *  utilities like \`bg-syncit-bond\`, \`text-syncit-ink\`, \`p-syncit-md\`
 *  are available alongside the existing shadcn HSL variables. */
export const syncitTokens = {
  colors: ${JSON.stringify(colors, null, 4)},
  spacing: ${JSON.stringify(mapUnit(spacing, "px"), null, 4)},
  radius: ${JSON.stringify(mapUnit(radius, "px"), null, 4)},
  fontSize: {
    "syncit-body-sm": ["${type.bodySmall}px", { lineHeight: "1.4" }],
    "syncit-body":    ["${type.body}px",      { lineHeight: "1.5" }],
    "syncit-button":  ["${type.button}px",    { lineHeight: "1.2" }],
    "syncit-heading": ["${type.heading}px",   { lineHeight: "1.3" }],
    "syncit-title":   ["${type.title}px",     { lineHeight: "1.2" }],
  },
  minHeight: {
    tap: "${tap}px",
  },
  fontFamily: {
    "syncit-body":    ["var(--font-body)", "system-ui", "sans-serif"],
    "syncit-display": ["var(--font-display)", "system-ui", "sans-serif"],
  },
  fontConfig: ${JSON.stringify(fonts, null, 4)},
};
`;
  await ensureDir(out);
  await writeFile(out, body);
  console.log(`  wrote ${rel(out)}`);
}

function mapUnit(obj, unit) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    out[k] = typeof v === "number" ? `${v}${unit}` : v;
  }
  return out;
}

async function writeMobileTheme(tokens) {
  const out = join(REPO, "mobile/src/theme.ts");
  const c = colorHexMap(tokens);
  const t = tokens.type;
  const s = tokens.spacing;
  const r = tokens.radius;
  const tap = tokens.tap.min;

  const body = `// GENERATED by packages/tokens/generate.mjs — do not edit by hand.
// Source: packages/tokens/tokens.json. Regenerate with:
//   npm run tokens:build
//
// One tokens file — every screen imports from here so future re-skinning
// is a single edit. Values chosen for a low-tech field user on a mid-
// range Android phone under variable lighting:
//   * 56px minimum tap target — matches Material 'large' spec and is
//     comfortable for users wearing gloves. Brief requires 56px min.
//   * 18px body minimum — legible at arm's length in bright sunlight;
//     16px was too small in field trials.
//   * Bond-green primary (${c.bond}) — carried over from Syncit brand
//     ramp; every other status colour is picked to sit against it.

export const theme = {
  colors: {
    // Syncit brand ramp
    bond:      "${c.bond}",
    kiln:      "${c.kiln}",
    set:       "${c.set}",
    cure:      "${c.cure}",
    fault:     "${c.fault}",
    bench:     "${c.bench}",
    ink:       "${c.ink}",
    inkMuted:  "${c.inkMuted}",
    line:      "${c.line}",
    curBg:     "${c.curBg}",
    faultBg:   "${c.faultBg}",
    white:     "${c.white}",

    // Legacy aliases — every existing screen imports \`primary\`,
    // \`background\`, \`textMuted\` etc. Kept pointing at the brand ramp
    // so nothing breaks on regeneration. New code should reference the
    // ramp names directly (\`bond\`, \`bench\`, \`inkMuted\`).
    primary:    "${c.bond}",
    primaryOn:  "${c.white}",
    background: "${c.white}",
    surface:    "${c.bench}",
    text:       "${c.ink}",
    textMuted:  "${c.inkMuted}",
    border:     "${c.line}",
    danger:     "${c.fault}",
    dangerBg:   "${c.faultBg}",
    success:    "${c.kiln}",
    focus:      "${c.kiln}",
  },
  // Minimum tap target — brief requires ${tap}px, matches Material spec
  // for "large" buttons and is comfortable for users wearing gloves.
  tap: ${tap},
  radius: ${r.md},
  radii: {
    sm:   ${r.sm},
    md:   ${r.md},
    lg:   ${r.lg},
    pill: ${r.pill},
  },
  spacing: {
    xs: ${s.xs},
    sm: ${s.sm},
    md: ${s.md},
    lg: ${s.lg},
    xl: ${s.xl},
  },
  type: {
    // 16 body minimum per brief; larger scale for titles because these
    // users often hold the phone at arm's length.
    bodySmall: ${t.bodySmall},
    body:      ${t.body},
    button:    ${t.button},
    heading:   ${t.heading},
    title:     ${t.title},
  },
} as const;

export type Theme = typeof theme;
`;

  await ensureDir(out);
  await writeFile(out, body);
  console.log(`  wrote ${rel(out)}`);
}

function rel(p) {
  return p.replace(REPO + "/", "");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
