// GENERATED by packages/tokens/generate.mjs — do not edit by hand.
// Source: packages/tokens/tokens.json.

/** Consumed by tailwind.config.ts under the `syncit` namespace so
 *  utilities like `bg-syncit-bond`, `text-syncit-ink`, `p-syncit-md`
 *  are available alongside the existing shadcn HSL variables. */
export const syncitTokens = {
  colors: {
    "bond": "#093D30",
    "kiln": "#12876C",
    "set": "#3DDC97",
    "cure": "#B96A00",
    "fault": "#B42318",
    "bench": "#F5F7F6",
    "ink": "#0B1D18",
    "inkMuted": "#5A6B65",
    "line": "#D8DEDC",
    "curBg": "#FEF3C7",
    "faultBg": "#FEE4E2",
    "white": "#FFFFFF"
},
  spacing: {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px"
},
  radius: {
    "sm": "6px",
    "md": "12px",
    "lg": "20px",
    "pill": "999px"
},
  fontSize: {
    "syncit-body-sm": ["16px", { lineHeight: "1.4" }],
    "syncit-body":    ["18px",      { lineHeight: "1.5" }],
    "syncit-button":  ["18px",    { lineHeight: "1.2" }],
    "syncit-heading": ["22px",   { lineHeight: "1.3" }],
    "syncit-title":   ["28px",     { lineHeight: "1.2" }],
  },
  minHeight: {
    tap: "56px",
  },
  fontFamily: {
    "syncit-body":    ["var(--font-body)", "system-ui", "sans-serif"],
    "syncit-display": ["var(--font-display)", "system-ui", "sans-serif"],
  },
  fontConfig: {
    "body": "Inter",
    "display": "Inter Tight"
},
};
