import { supabase } from "./supabase";

// Minimal roster returned by the `get_profile_directory` RPC — id +
// ownerName + role for every active user. Restricted server-side to
// ADMIN and FACTORY callers (see migration
// 20260824120000_add_profile_directory_read). STAFF callers get an
// empty result set; renderers show "Unknown user" for anyone they
// can't resolve.
//
// Why an in-memory cache: the directory is read on every list render
// (order cards, timelines, comments, payment history). Refetching per
// screen would hammer the RPC. The roster changes only when an admin
// adds/deactivates a user — rare enough that the sign-out that
// AuthContext triggers on session change is a fine invalidation point.

export type ProfileDirectoryEntry = {
  id: string;
  ownerName: string;
  role: string;
  /** Nullable — some team members may not have a phone on file yet.
   *  Renderers gate tap-to-call on this being present. */
  phone: string | null;
};

let cache: Map<string, ProfileDirectoryEntry> | null = null;
let inflight: Promise<Map<string, ProfileDirectoryEntry>> | null = null;

export async function getProfileDirectory(): Promise<
  Map<string, ProfileDirectoryEntry>
> {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = (async () => {
    // Cast: get_profile_directory is added by migration
    // 20260824120000_add_profile_directory_read; database.types.ts is
    // regenerated by CI (see commit a5c9a60). Until the regen lands
    // in the client bundle, the RPC name isn't in the generated union.
    const { data, error } = await (supabase.rpc as unknown as (
      fn: string,
    ) => Promise<{ data: ProfileDirectoryEntry[] | null; error: unknown }>)(
      "get_profile_directory",
    );
    if (error) {
      // Do not throw — a failed directory lookup must not break the
      // list. Renderers already handle a missing name as "Unknown user".
      inflight = null;
      return new Map();
    }
    const map = new Map<string, ProfileDirectoryEntry>();
    for (const row of (data ?? []) as ProfileDirectoryEntry[]) {
      map.set(row.id, {
        id: row.id,
        ownerName: row.ownerName,
        role: row.role,
        phone: row.phone ?? null,
      });
    }
    cache = map;
    inflight = null;
    return map;
  })();
  return inflight;
}

/** Drop the in-memory cache — call on sign-out and after admin edits. */
export function invalidateProfileDirectory(): void {
  cache = null;
  inflight = null;
}
